aws/amazon-s3-encryption-client-dotnet

src/Amazon.Extensions.S3.Encryption.csproj

*Issue #, if available:*
*Description of changes:*
Minor version bump to support assembly rename.
Verified that assembly is signed correctly after changing the name.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Update assembly version to 1.1.0

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general-question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/closed-issue-message.yml
.github/workflows/stale_issues.yml

*Issue #, if available:*
N/A
*Description of changes:*
Add `.github` folder to configure GitHub workflows.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

chore: Add .github folder to configure GitHub workflows

---

src/Amazon.Extensions.S3.Encryption.csproj

Use workaround suggested [here](https://github.com/dotnet/msbuild/issues/5985) unblock release pipeline 
`dotnet build .\src\Amazon.Extensions.S3.Encryption.csproj` succeeds

Fix build failure occurring while using .NET 5 CLI

---

src/Amazon.Extensions.S3.Encryption.csproj

BouncyCastle to 1.8.9
Portable.BouncyCastle to 1.8.9
https://github.com/aws/amazon-s3-encryption-client-dotnet/issues/11
Unit tests & Integration tests for `net35`, `net45`, `netstandard2.0` & `netcoreapp3.1`

fix: update BouncyCastle dependency versions

---

CHANGELOG.md
src/Amazon.Extensions.S3.Encryption.csproj

```
dotnet build .\src\Amazon.Extensions.S3.Encryption.csproj
```

fix: update AWSSDK.Core, AWSSDK.S3, AWSSDK.KeyManagementService versions

---

test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetFramework.csproj
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetStandard.csproj

These deps will come along with the main Amazon.Extensions.S3.Encryption.csproj.
`dotnet build`

fix: remove explicit Core, S3 and KMS deps

---

src/Amazon.Extensions.S3.Encryption.csproj

For .NET Framework 4.5, .NET Standard 2.0 and .NET Core 3.1
- 1.8.10
https://github.com/aws/amazon-s3-encryption-client-dotnet/issues/11
Integ tests

chore: update BouncyCastle dependency versions

---

CHANGELOG.md

Update change log for fixing aws ses decryption bug

Update change log for fixing aws ses decryption bug

---

CHANGELOG.md

Updated ChangeLog v2.1.0 - Added ServiceURL option for KMS client
Changelogs are updated in a subsequent commit.
N/A

Updated ChangeLog v2.1.0 - Added ServiceURL option for KMS client

---

src/Amazon.Extensions.S3.Encryption.csproj
src/AmazonS3EncryptionClient.cs
src/AmazonS3EncryptionClientV2.cs
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetFramework.csproj
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetStandard.csproj

chore: Update User-Agent string
Verified that the UA string is set appropriately based on the client version and the currently assembly version
* `lib/amazon-extensions-s3-encryption#2.1.1.0 ft/S3CryptoV1n`
* `lib/amazon-extensions-s3-encryption#2.1.1.0 ft/S3CryptoV2`

[UA update] chore: Update User-Agent string

---

src/Amazon.Extensions.S3.Encryption.csproj
src/AmazonS3EncryptionClient.cs
src/AmazonS3EncryptionClientV2.cs
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetFramework.csproj
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetStandard.csproj

[UA update] [Merge dev -> main] chore: Update User-Agent string (#51)

---

.github/workflows/aws-ci.yml
buildtools/ci.buildspec.yml

* Added GitHub workflow that runs unit tests and integ tests using the testing infrastructure on PRs targeting `v4sdk-release`, `v4sdk-development` and feature branches. `v4sdk-release` and `v4sdk-development` will be switched to `main` and `dev` once V4 goes GA.
* Added a buildspec file that the testing infrastructure will use to run the tests. The buildspec adds mono to the base image.

ci: onboard the repo to the testing infra

---

.github/workflows/create-release-pr.yml
.github/workflows/sync-main-dev.yml

This PR follows in the footsteps of https://github.com/awslabs/aws-dotnet-messaging/pull/112 and adds support for automated versioning and changelog creation using AutoVer.
The added workflows are basically a copy/paste with changes to the branch names. Instead of using `dev` and `main`, we will be using `v4sdk-development` and `v4sdk-release` until the V4 upgrade is complete.
Add support for automated versioning and changelog creation instead of manually updating the version numbers in the project files.
Tested using a forked repo

ci: add support for automated versioning and changelog creation

---

.autover/changes/31934f1f-d986-4d98-8f0f-e3008f43c7ff.json

Add a change file in preparation for `preview.2`

add change file for 3.0.0-preview.2

---

CHANGELOG.md
src/Amazon.Extensions.S3.Encryption.csproj
src/Internal/SetupDecryptionHandler.cs

*Issue #, if available:*
DOTNET-7990
*Description of changes:*
Sync `dev` and `v4sdk-development`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Sync `dev` and `v4sdk-development`

---

.autover/changes/eb8882c7-e663-4afd-be44-0e34064f89ea.json
src/Amazon.Extensions.S3.Encryption.csproj
src/AmazonS3EncryptionClientBase.cs
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetFramework.csproj
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetStandard.csproj

1. DOTNET-8029
2. Update AWS SDK to Preview 11
Existing tests pass

Update AWS SDK to Preview 11

---

.github/workflows/aws-ci.yml
.github/workflows/change-file-in-pr.yml
.github/workflows/closed-issue-message.yml
.github/workflows/create-release-pr.yml
.github/workflows/doc-site.yml
.github/workflows/handle-stale-discussions.yml
.github/workflows/issue-regression-labeler.yml
.github/workflows/stale_issues.yml
.github/workflows/sync-main-dev.yml

*Issue #, if available:* DOTNET-8045
*Description of changes:*
Update workflows to be pinned to sha. This is following the best practices https://www.stepsecurity.io/blog/pinning-github-actions-for-enhanced-security-a-complete-guide#:~:text=Action%20pinning%20with%20specific%20commit,point%20to%20different%20code%20versions
Created 2 scripts to update everything
```
function Convert-TagToCommit {
param (
[string]$owner,
[string]$repo,
[string]$tag
)
try {
$result = gh api "repos/$owner/$repo/git/refs/tags/$tag" | ConvertFrom-Json
return $result.object.sha
}
catch {
Write-Warning "Could not resolve tag $tag for $owner/$repo"
return $null
}
}
$workflowFiles = Get-ChildItem -Path ".github/workflows" -Filter "*.yml" -Recurse
foreach ($file in $workflowFiles) {
$content = Get-Content …
```

update actions to use commit hash

---

.github/workflows/doc-site.yml

Sync up V3 and V4 branches

---

.autover/changes/02f6c3fa-e307-421c-b396-28ef7f30a128.json
src/Amazon.Extensions.S3.Encryption.csproj
src/Internal/UserAgentHandler.cs
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetFramework.csproj
test/IntegrationTests/Amazon.Extensions.S3.Encryption.IntegrationTests.NetStandard.csproj

* Update .NET SDK to v4.0.0
* Use UserAgentDetails to add s3 encryption user agent

chore: update .NET SDK to v4.0.0

---

.github/workflows/doc-site.yml

**Description**
Fix doc site which was broken while merging changes during yesterday's sync up

chore: fix doc site

---

.github/workflows/doc-site.yml

Sync doc site workflow with other HLLs

chore: update doc site workflow

---

docs/docfx.json

chore: update docfx target framework
